[tools]
go = "1.27.1"
node = "24.21.0"
pnpm = "12.8.1"
task = "3.53.1"
golangci-lint = "2.14.0"
"aqua:fe3dback/go-arch-lint" = "1.19.0"
"aqua:pressly/goose" = "3.28.0"
"aqua:koalaman/shellcheck" = "0.11.0"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "2.8.0"
"go:go.uber.org/mock/mockgen" = "0.6.0"
