// Code generated by MockGen. DO NOT EDIT.
// Source: git.alva.dev/alva/harness-telemetry/internal/application/passkeys (interfaces: Users,Passkeys,Ceremonies,WebAuthn,SessionService,Clock)
//
// Generated by this command:
//
//	mockgen -destination=mock/external.go -package=mock . Users,Passkeys,Ceremonies,WebAuthn,SessionService,Clock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	passkeys "git.alva.dev/alva/harness-telemetry/internal/application/passkeys"
	domain "git.alva.dev/alva/harness-telemetry/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
	isgomock struct{}
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUsers) GetByID(ctx context.Context, id uuid.UUID) (domain.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsersMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsers)(nil).GetByID), ctx, id)
}

// GetByWebAuthnID mocks base method.
func (m *MockUsers) GetByWebAuthnID(ctx context.Context, webAuthnUserID []byte) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWebAuthnID", ctx, webAuthnUserID)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWebAuthnID indicates an expected call of GetByWebAuthnID.
func (mr *MockUsersMockRecorder) GetByWebAuthnID(ctx, webAuthnUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWebAuthnID", reflect.TypeOf((*MockUsers)(nil).GetByWebAuthnID), ctx, webAuthnUserID)
}

// GetWebAuthnID mocks base method.
func (m *MockUsers) GetWebAuthnID(ctx context.Context, id uuid.UUID) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebAuthnID", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebAuthnID indicates an expected call of GetWebAuthnID.
func (mr *MockUsersMockRecorder) GetWebAuthnID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebAuthnID", reflect.TypeOf((*MockUsers)(nil).GetWebAuthnID), ctx, id)
}

// TouchLogin mocks base method.
func (m *MockUsers) TouchLogin(ctx context.Context, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLogin", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLogin indicates an expected call of TouchLogin.
func (mr *MockUsersMockRecorder) TouchLogin(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLogin", reflect.TypeOf((*MockUsers)(nil).TouchLogin), ctx, id, at)
}

// MockPasskeys is a mock of Passkeys interface.
type MockPasskeys struct {
	ctrl     *gomock.Controller
	recorder *MockPasskeysMockRecorder
	isgomock struct{}
}

// MockPasskeysMockRecorder is the mock recorder for MockPasskeys.
type MockPasskeysMockRecorder struct {
	mock *MockPasskeys
}

// NewMockPasskeys creates a new mock instance.
func NewMockPasskeys(ctrl *gomock.Controller) *MockPasskeys {
	mock := &MockPasskeys{ctrl: ctrl}
	mock.recorder = &MockPasskeysMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasskeys) EXPECT() *MockPasskeysMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasskeys) Create(ctx context.Context, passkey domain.Passkey) (domain.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, passkey)
	ret0, _ := ret[0].(domain.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPasskeysMockRecorder) Create(ctx, passkey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasskeys)(nil).Create), ctx, passkey)
}

// Delete mocks base method.
func (m *MockPasskeys) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPasskeysMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasskeys)(nil).Delete), ctx, id, userID)
}

// ListByUser mocks base method.
func (m *MockPasskeys) ListByUser(ctx context.Context, userID uuid.UUID) ([]domain.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockPasskeysMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockPasskeys)(nil).ListByUser), ctx, userID)
}

// RecordUse mocks base method.
func (m *MockPasskeys) RecordUse(ctx context.Context, id uuid.UUID, signCount uint32, backupState bool, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordUse", ctx, id, signCount, backupState, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordUse indicates an expected call of RecordUse.
func (mr *MockPasskeysMockRecorder) RecordUse(ctx, id, signCount, backupState, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUse", reflect.TypeOf((*MockPasskeys)(nil).RecordUse), ctx, id, signCount, backupState, at)
}

// MockCeremonies is a mock of Ceremonies interface.
type MockCeremonies struct {
	ctrl     *gomock.Controller
	recorder *MockCeremoniesMockRecorder
	isgomock struct{}
}

// MockCeremoniesMockRecorder is the mock recorder for MockCeremonies.
type MockCeremoniesMockRecorder struct {
	mock *MockCeremonies
}

// NewMockCeremonies creates a new mock instance.
func NewMockCeremonies(ctrl *gomock.Controller) *MockCeremonies {
	mock := &MockCeremonies{ctrl: ctrl}
	mock.recorder = &MockCeremoniesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCeremonies) EXPECT() *MockCeremoniesMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockCeremonies) Save(ctx context.Context, kind domain.CeremonyKind, userID *uuid.UUID, passkeyName *string, sessionData []byte, expiresAt time.Time) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, kind, userID, passkeyName, sessionData, expiresAt)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockCeremoniesMockRecorder) Save(ctx, kind, userID, passkeyName, sessionData, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCeremonies)(nil).Save), ctx, kind, userID, passkeyName, sessionData, expiresAt)
}

// Take mocks base method.
func (m *MockCeremonies) Take(ctx context.Context, id uuid.UUID, kind domain.CeremonyKind) (*uuid.UUID, *string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", ctx, id, kind)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].([]byte)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Take indicates an expected call of Take.
func (mr *MockCeremoniesMockRecorder) Take(ctx, id, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockCeremonies)(nil).Take), ctx, id, kind)
}

// MockWebAuthn is a mock of WebAuthn interface.
type MockWebAuthn struct {
	ctrl     *gomock.Controller
	recorder *MockWebAuthnMockRecorder
	isgomock struct{}
}

// MockWebAuthnMockRecorder is the mock recorder for MockWebAuthn.
type MockWebAuthnMockRecorder struct {
	mock *MockWebAuthn
}

// NewMockWebAuthn creates a new mock instance.
func NewMockWebAuthn(ctrl *gomock.Controller) *MockWebAuthn {
	mock := &MockWebAuthn{ctrl: ctrl}
	mock.recorder = &MockWebAuthnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAuthn) EXPECT() *MockWebAuthnMockRecorder {
	return m.recorder
}

// BeginLogin mocks base method.
func (m *MockWebAuthn) BeginLogin() ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginLogin")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginLogin indicates an expected call of BeginLogin.
func (mr *MockWebAuthnMockRecorder) BeginLogin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginLogin", reflect.TypeOf((*MockWebAuthn)(nil).BeginLogin))
}

// BeginRegistration mocks base method.
func (m *MockWebAuthn) BeginRegistration(user domain.User, webauthnUserID []byte, existing []domain.Passkey) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginRegistration", user, webauthnUserID, existing)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginRegistration indicates an expected call of BeginRegistration.
func (mr *MockWebAuthnMockRecorder) BeginRegistration(user, webauthnUserID, existing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginRegistration", reflect.TypeOf((*MockWebAuthn)(nil).BeginRegistration), user, webauthnUserID, existing)
}

// FinishLogin mocks base method.
func (m *MockWebAuthn) FinishLogin(sessionData, responseJSON []byte, lookup passkeys.PasskeyLookup) (uuid.UUID, []byte, uint32, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishLogin", sessionData, responseJSON, lookup)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(uint32)
	ret3, _ := ret[3].(bool)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// FinishLogin indicates an expected call of FinishLogin.
func (mr *MockWebAuthnMockRecorder) FinishLogin(sessionData, responseJSON, lookup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishLogin", reflect.TypeOf((*MockWebAuthn)(nil).FinishLogin), sessionData, responseJSON, lookup)
}

// FinishRegistration mocks base method.
func (m *MockWebAuthn) FinishRegistration(user domain.User, webauthnUserID []byte, existing []domain.Passkey, sessionData, responseJSON []byte) (domain.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishRegistration", user, webauthnUserID, existing, sessionData, responseJSON)
	ret0, _ := ret[0].(domain.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishRegistration indicates an expected call of FinishRegistration.
func (mr *MockWebAuthnMockRecorder) FinishRegistration(user, webauthnUserID, existing, sessionData, responseJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishRegistration", reflect.TypeOf((*MockWebAuthn)(nil).FinishRegistration), user, webauthnUserID, existing, sessionData, responseJSON)
}

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockSessionService) Open(ctx context.Context, userID uuid.UUID, userAgent string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, userID, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Open indicates an expected call of Open.
func (mr *MockSessionServiceMockRecorder) Open(ctx, userID, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockSessionService)(nil).Open), ctx, userID, userAgent)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
