// Code generated by MockGen. DO NOT EDIT.
// Source: git.alva.dev/alva/harness-telemetry/internal/delivery/http/handler (interfaces: Auth,Sessions,Users,Passkeys,Keys,Settings,Releases)
//
// Generated by this command:
//
//	mockgen -destination=mock/external.go -package=mock . Auth,Sessions,Users,Passkeys,Keys,Settings,Releases
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	json "encoding/json"
	io "io"
	reflect "reflect"
	time "time"

	keys "git.alva.dev/alva/harness-telemetry/internal/application/keys"
	domain "git.alva.dev/alva/harness-telemetry/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
	isgomock struct{}
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockAuth) ChangePassword(ctx context.Context, userID, sessionID uuid.UUID, current, next string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, sessionID, current, next)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthMockRecorder) ChangePassword(ctx, userID, sessionID, current, next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuth)(nil).ChangePassword), ctx, userID, sessionID, current, next)
}

// LoginWithPassword mocks base method.
func (m *MockAuth) LoginWithPassword(ctx context.Context, email, password, userAgent string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithPassword", ctx, email, password, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoginWithPassword indicates an expected call of LoginWithPassword.
func (mr *MockAuthMockRecorder) LoginWithPassword(ctx, email, password, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithPassword", reflect.TypeOf((*MockAuth)(nil).LoginWithPassword), ctx, email, password, userAgent)
}

// Me mocks base method.
func (m *MockAuth) Me(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx, userID)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockAuthMockRecorder) Me(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockAuth)(nil).Me), ctx, userID)
}

// MockSessions is a mock of Sessions interface.
type MockSessions struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsMockRecorder
	isgomock struct{}
}

// MockSessionsMockRecorder is the mock recorder for MockSessions.
type MockSessionsMockRecorder struct {
	mock *MockSessions
}

// NewMockSessions creates a new mock instance.
func NewMockSessions(ctrl *gomock.Controller) *MockSessions {
	mock := &MockSessions{ctrl: ctrl}
	mock.recorder = &MockSessionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessions) EXPECT() *MockSessionsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSessions) Close(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSessionsMockRecorder) Close(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSessions)(nil).Close), ctx, sessionID)
}

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
	isgomock struct{}
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// AcceptInvite mocks base method.
func (m *MockUsers) AcceptInvite(ctx context.Context, token, password, userAgent string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", ctx, token, password, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockUsersMockRecorder) AcceptInvite(ctx, token, password, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockUsers)(nil).AcceptInvite), ctx, token, password, userAgent)
}

// CompleteReset mocks base method.
func (m *MockUsers) CompleteReset(ctx context.Context, token, password, userAgent string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteReset", ctx, token, password, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CompleteReset indicates an expected call of CompleteReset.
func (mr *MockUsersMockRecorder) CompleteReset(ctx, token, password, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteReset", reflect.TypeOf((*MockUsers)(nil).CompleteReset), ctx, token, password, userAgent)
}

// Invite mocks base method.
func (m *MockUsers) Invite(ctx context.Context, actorID uuid.UUID, email, name string) (domain.UserView, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invite", ctx, actorID, email, name)
	ret0, _ := ret[0].(domain.UserView)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Invite indicates an expected call of Invite.
func (mr *MockUsersMockRecorder) Invite(ctx, actorID, email, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invite", reflect.TypeOf((*MockUsers)(nil).Invite), ctx, actorID, email, name)
}

// IssueReset mocks base method.
func (m *MockUsers) IssueReset(ctx context.Context, actorID, userID uuid.UUID) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueReset", ctx, actorID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueReset indicates an expected call of IssueReset.
func (mr *MockUsersMockRecorder) IssueReset(ctx, actorID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueReset", reflect.TypeOf((*MockUsers)(nil).IssueReset), ctx, actorID, userID)
}

// List mocks base method.
func (m *MockUsers) List(ctx context.Context) ([]domain.UserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.UserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUsersMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUsers)(nil).List), ctx)
}

// LookupLink mocks base method.
func (m *MockUsers) LookupLink(ctx context.Context, token string, kind domain.LinkKind) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupLink", ctx, token, kind)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LookupLink indicates an expected call of LookupLink.
func (mr *MockUsersMockRecorder) LookupLink(ctx, token, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupLink", reflect.TypeOf((*MockUsers)(nil).LookupLink), ctx, token, kind)
}

// ReissueInvite mocks base method.
func (m *MockUsers) ReissueInvite(ctx context.Context, actorID, userID uuid.UUID) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReissueInvite", ctx, actorID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReissueInvite indicates an expected call of ReissueInvite.
func (mr *MockUsersMockRecorder) ReissueInvite(ctx, actorID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReissueInvite", reflect.TypeOf((*MockUsers)(nil).ReissueInvite), ctx, actorID, userID)
}

// RevokeInvite mocks base method.
func (m *MockUsers) RevokeInvite(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeInvite", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeInvite indicates an expected call of RevokeInvite.
func (mr *MockUsersMockRecorder) RevokeInvite(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeInvite", reflect.TypeOf((*MockUsers)(nil).RevokeInvite), ctx, userID)
}

// MockPasskeys is a mock of Passkeys interface.
type MockPasskeys struct {
	ctrl     *gomock.Controller
	recorder *MockPasskeysMockRecorder
	isgomock struct{}
}

// MockPasskeysMockRecorder is the mock recorder for MockPasskeys.
type MockPasskeysMockRecorder struct {
	mock *MockPasskeys
}

// NewMockPasskeys creates a new mock instance.
func NewMockPasskeys(ctrl *gomock.Controller) *MockPasskeys {
	mock := &MockPasskeys{ctrl: ctrl}
	mock.recorder = &MockPasskeysMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasskeys) EXPECT() *MockPasskeysMockRecorder {
	return m.recorder
}

// BeginLogin mocks base method.
func (m *MockPasskeys) BeginLogin(ctx context.Context) (uuid.UUID, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginLogin", ctx)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginLogin indicates an expected call of BeginLogin.
func (mr *MockPasskeysMockRecorder) BeginLogin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginLogin", reflect.TypeOf((*MockPasskeys)(nil).BeginLogin), ctx)
}

// BeginRegistration mocks base method.
func (m *MockPasskeys) BeginRegistration(ctx context.Context, userID uuid.UUID, name string) (uuid.UUID, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginRegistration", ctx, userID, name)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginRegistration indicates an expected call of BeginRegistration.
func (mr *MockPasskeysMockRecorder) BeginRegistration(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginRegistration", reflect.TypeOf((*MockPasskeys)(nil).BeginRegistration), ctx, userID, name)
}

// Delete mocks base method.
func (m *MockPasskeys) Delete(ctx context.Context, userID, passkeyID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, passkeyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPasskeysMockRecorder) Delete(ctx, userID, passkeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasskeys)(nil).Delete), ctx, userID, passkeyID)
}

// FinishLogin mocks base method.
func (m *MockPasskeys) FinishLogin(ctx context.Context, ceremonyID uuid.UUID, responseJSON []byte, userAgent string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishLogin", ctx, ceremonyID, responseJSON, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FinishLogin indicates an expected call of FinishLogin.
func (mr *MockPasskeysMockRecorder) FinishLogin(ctx, ceremonyID, responseJSON, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishLogin", reflect.TypeOf((*MockPasskeys)(nil).FinishLogin), ctx, ceremonyID, responseJSON, userAgent)
}

// FinishRegistration mocks base method.
func (m *MockPasskeys) FinishRegistration(ctx context.Context, userID, ceremonyID uuid.UUID, responseJSON []byte) (domain.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishRegistration", ctx, userID, ceremonyID, responseJSON)
	ret0, _ := ret[0].(domain.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishRegistration indicates an expected call of FinishRegistration.
func (mr *MockPasskeysMockRecorder) FinishRegistration(ctx, userID, ceremonyID, responseJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishRegistration", reflect.TypeOf((*MockPasskeys)(nil).FinishRegistration), ctx, userID, ceremonyID, responseJSON)
}

// List mocks base method.
func (m *MockPasskeys) List(ctx context.Context, userID uuid.UUID) ([]domain.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]domain.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPasskeysMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPasskeys)(nil).List), ctx, userID)
}

// MockKeys is a mock of Keys interface.
type MockKeys struct {
	ctrl     *gomock.Controller
	recorder *MockKeysMockRecorder
	isgomock struct{}
}

// MockKeysMockRecorder is the mock recorder for MockKeys.
type MockKeysMockRecorder struct {
	mock *MockKeys
}

// NewMockKeys creates a new mock instance.
func NewMockKeys(ctrl *gomock.Controller) *MockKeys {
	mock := &MockKeys{ctrl: ctrl}
	mock.recorder = &MockKeysMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeys) EXPECT() *MockKeysMockRecorder {
	return m.recorder
}

// IssueMCPKey mocks base method.
func (m *MockKeys) IssueMCPKey(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueMCPKey", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueMCPKey indicates an expected call of IssueMCPKey.
func (mr *MockKeysMockRecorder) IssueMCPKey(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueMCPKey", reflect.TypeOf((*MockKeys)(nil).IssueMCPKey), ctx, userID)
}

// KeysStatus mocks base method.
func (m *MockKeys) KeysStatus(ctx context.Context, userID uuid.UUID) (keys.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeysStatus", ctx, userID)
	ret0, _ := ret[0].(keys.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeysStatus indicates an expected call of KeysStatus.
func (mr *MockKeysMockRecorder) KeysStatus(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeysStatus", reflect.TypeOf((*MockKeys)(nil).KeysStatus), ctx, userID)
}

// ReissueIngestToken mocks base method.
func (m *MockKeys) ReissueIngestToken(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReissueIngestToken", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReissueIngestToken indicates an expected call of ReissueIngestToken.
func (mr *MockKeysMockRecorder) ReissueIngestToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReissueIngestToken", reflect.TypeOf((*MockKeys)(nil).ReissueIngestToken), ctx, userID)
}

// RevokeMCPKey mocks base method.
func (m *MockKeys) RevokeMCPKey(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeMCPKey", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeMCPKey indicates an expected call of RevokeMCPKey.
func (mr *MockKeysMockRecorder) RevokeMCPKey(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeMCPKey", reflect.TypeOf((*MockKeys)(nil).RevokeMCPKey), ctx, userID)
}

// MockSettings is a mock of Settings interface.
type MockSettings struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsMockRecorder
	isgomock struct{}
}

// MockSettingsMockRecorder is the mock recorder for MockSettings.
type MockSettingsMockRecorder struct {
	mock *MockSettings
}

// NewMockSettings creates a new mock instance.
func NewMockSettings(ctrl *gomock.Controller) *MockSettings {
	mock := &MockSettings{ctrl: ctrl}
	mock.recorder = &MockSettingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettings) EXPECT() *MockSettingsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSettings) Get(ctx context.Context, userID uuid.UUID) (domain.TelemetrySettings, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.TelemetrySettings)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockSettingsMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettings)(nil).Get), ctx, userID)
}

// Update mocks base method.
func (m *MockSettings) Update(ctx context.Context, userID uuid.UUID, document json.RawMessage, expectedVersion int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, document, expectedVersion)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSettingsMockRecorder) Update(ctx, userID, document, expectedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettings)(nil).Update), ctx, userID, document, expectedVersion)
}

// MockReleases is a mock of Releases interface.
type MockReleases struct {
	ctrl     *gomock.Controller
	recorder *MockReleasesMockRecorder
	isgomock struct{}
}

// MockReleasesMockRecorder is the mock recorder for MockReleases.
type MockReleasesMockRecorder struct {
	mock *MockReleases
}

// NewMockReleases creates a new mock instance.
func NewMockReleases(ctrl *gomock.Controller) *MockReleases {
	mock := &MockReleases{ctrl: ctrl}
	mock.recorder = &MockReleasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleases) EXPECT() *MockReleasesMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockReleases) Open(ctx context.Context, name string) (io.ReadCloser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Open indicates an expected call of Open.
func (mr *MockReleasesMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockReleases)(nil).Open), ctx, name)
}
