// Code generated by MockGen. DO NOT EDIT.
// Source: external.go
//
// Generated by this command:
//
//	mockgen -source=external.go -destination=./mock/external.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "git.alva.dev/alva/harness-telemetry/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
	isgomock struct{}
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// CreateActive mocks base method.
func (m *MockUsers) CreateActive(ctx context.Context, email domain.Email, name domain.UserName, passwordHash string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActive", ctx, email, name, passwordHash)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActive indicates an expected call of CreateActive.
func (mr *MockUsersMockRecorder) CreateActive(ctx, email, name, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActive", reflect.TypeOf((*MockUsers)(nil).CreateActive), ctx, email, name, passwordHash)
}

// CreateInvited mocks base method.
func (m *MockUsers) CreateInvited(ctx context.Context, email domain.Email, name domain.UserName) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvited", ctx, email, name)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvited indicates an expected call of CreateInvited.
func (mr *MockUsersMockRecorder) CreateInvited(ctx, email, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvited", reflect.TypeOf((*MockUsers)(nil).CreateInvited), ctx, email, name)
}

// DeleteInvited mocks base method.
func (m *MockUsers) DeleteInvited(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvited", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvited indicates an expected call of DeleteInvited.
func (mr *MockUsersMockRecorder) DeleteInvited(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvited", reflect.TypeOf((*MockUsers)(nil).DeleteInvited), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUsers) GetByEmail(ctx context.Context, email domain.Email) (domain.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUsersMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUsers)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUsers) GetByID(ctx context.Context, id uuid.UUID) (domain.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsersMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsers)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockUsers) List(ctx context.Context) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUsersMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUsers)(nil).List), ctx)
}

// SetPassword mocks base method.
func (m *MockUsers) SetPassword(ctx context.Context, id uuid.UUID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPassword", ctx, id, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPassword indicates an expected call of SetPassword.
func (mr *MockUsersMockRecorder) SetPassword(ctx, id, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPassword", reflect.TypeOf((*MockUsers)(nil).SetPassword), ctx, id, passwordHash)
}

// TouchLogin mocks base method.
func (m *MockUsers) TouchLogin(ctx context.Context, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLogin", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLogin indicates an expected call of TouchLogin.
func (mr *MockUsersMockRecorder) TouchLogin(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLogin", reflect.TypeOf((*MockUsers)(nil).TouchLogin), ctx, id, at)
}

// MockLinks is a mock of Links interface.
type MockLinks struct {
	ctrl     *gomock.Controller
	recorder *MockLinksMockRecorder
	isgomock struct{}
}

// MockLinksMockRecorder is the mock recorder for MockLinks.
type MockLinksMockRecorder struct {
	mock *MockLinks
}

// NewMockLinks creates a new mock instance.
func NewMockLinks(ctrl *gomock.Controller) *MockLinks {
	mock := &MockLinks{ctrl: ctrl}
	mock.recorder = &MockLinksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinks) EXPECT() *MockLinksMockRecorder {
	return m.recorder
}

// DeleteUnused mocks base method.
func (m *MockLinks) DeleteUnused(ctx context.Context, userID uuid.UUID, kind domain.LinkKind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnused", ctx, userID, kind)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUnused indicates an expected call of DeleteUnused.
func (mr *MockLinksMockRecorder) DeleteUnused(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnused", reflect.TypeOf((*MockLinks)(nil).DeleteUnused), ctx, userID, kind)
}

// GetActiveForUser mocks base method.
func (m *MockLinks) GetActiveForUser(ctx context.Context, userID uuid.UUID, kind domain.LinkKind) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveForUser", ctx, userID, kind)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveForUser indicates an expected call of GetActiveForUser.
func (mr *MockLinksMockRecorder) GetActiveForUser(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveForUser", reflect.TypeOf((*MockLinks)(nil).GetActiveForUser), ctx, userID, kind)
}

// GetByTokenHash mocks base method.
func (m *MockLinks) GetByTokenHash(ctx context.Context, tokenHash []byte) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockLinksMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockLinks)(nil).GetByTokenHash), ctx, tokenHash)
}

// MarkUsed mocks base method.
func (m *MockLinks) MarkUsed(ctx context.Context, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockLinksMockRecorder) MarkUsed(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockLinks)(nil).MarkUsed), ctx, id, at)
}

// Replace mocks base method.
func (m *MockLinks) Replace(ctx context.Context, userID uuid.UUID, kind domain.LinkKind, tokenHash []byte, createdBy uuid.UUID, expiresAt time.Time) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, userID, kind, tokenHash, createdBy, expiresAt)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockLinksMockRecorder) Replace(ctx, userID, kind, tokenHash, createdBy, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockLinks)(nil).Replace), ctx, userID, kind, tokenHash, createdBy, expiresAt)
}

// MocksessionRepository is a mock of sessionRepository interface.
type MocksessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksessionRepositoryMockRecorder
	isgomock struct{}
}

// MocksessionRepositoryMockRecorder is the mock recorder for MocksessionRepository.
type MocksessionRepositoryMockRecorder struct {
	mock *MocksessionRepository
}

// NewMocksessionRepository creates a new mock instance.
func NewMocksessionRepository(ctrl *gomock.Controller) *MocksessionRepository {
	mock := &MocksessionRepository{ctrl: ctrl}
	mock.recorder = &MocksessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionRepository) EXPECT() *MocksessionRepositoryMockRecorder {
	return m.recorder
}

// DeleteAllForUser mocks base method.
func (m *MocksessionRepository) DeleteAllForUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllForUser indicates an expected call of DeleteAllForUser.
func (mr *MocksessionRepositoryMockRecorder) DeleteAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllForUser", reflect.TypeOf((*MocksessionRepository)(nil).DeleteAllForUser), ctx, userID)
}

// MockpasswordHasher is a mock of passwordHasher interface.
type MockpasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordHasherMockRecorder
	isgomock struct{}
}

// MockpasswordHasherMockRecorder is the mock recorder for MockpasswordHasher.
type MockpasswordHasherMockRecorder struct {
	mock *MockpasswordHasher
}

// NewMockpasswordHasher creates a new mock instance.
func NewMockpasswordHasher(ctrl *gomock.Controller) *MockpasswordHasher {
	mock := &MockpasswordHasher{ctrl: ctrl}
	mock.recorder = &MockpasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordHasher) EXPECT() *MockpasswordHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockpasswordHasher) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockpasswordHasherMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockpasswordHasher)(nil).Hash), password)
}

// MocktokenIssuer is a mock of tokenIssuer interface.
type MocktokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MocktokenIssuerMockRecorder
	isgomock struct{}
}

// MocktokenIssuerMockRecorder is the mock recorder for MocktokenIssuer.
type MocktokenIssuerMockRecorder struct {
	mock *MocktokenIssuer
}

// NewMocktokenIssuer creates a new mock instance.
func NewMocktokenIssuer(ctrl *gomock.Controller) *MocktokenIssuer {
	mock := &MocktokenIssuer{ctrl: ctrl}
	mock.recorder = &MocktokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenIssuer) EXPECT() *MocktokenIssuerMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MocktokenIssuer) Hash(token string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", token)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MocktokenIssuerMockRecorder) Hash(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MocktokenIssuer)(nil).Hash), token)
}

// New mocks base method.
func (m *MocktokenIssuer) New() (string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// New indicates an expected call of New.
func (mr *MocktokenIssuerMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MocktokenIssuer)(nil).New))
}

// MocksessionOpener is a mock of sessionOpener interface.
type MocksessionOpener struct {
	ctrl     *gomock.Controller
	recorder *MocksessionOpenerMockRecorder
	isgomock struct{}
}

// MocksessionOpenerMockRecorder is the mock recorder for MocksessionOpener.
type MocksessionOpenerMockRecorder struct {
	mock *MocksessionOpener
}

// NewMocksessionOpener creates a new mock instance.
func NewMocksessionOpener(ctrl *gomock.Controller) *MocksessionOpener {
	mock := &MocksessionOpener{ctrl: ctrl}
	mock.recorder = &MocksessionOpenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionOpener) EXPECT() *MocksessionOpenerMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MocksessionOpener) Open(ctx context.Context, userID uuid.UUID, userAgent string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, userID, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Open indicates an expected call of Open.
func (mr *MocksessionOpenerMockRecorder) Open(ctx, userID, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MocksessionOpener)(nil).Open), ctx, userID, userAgent)
}

// Mockclock is a mock of clock interface.
type Mockclock struct {
	ctrl     *gomock.Controller
	recorder *MockclockMockRecorder
	isgomock struct{}
}

// MockclockMockRecorder is the mock recorder for Mockclock.
type MockclockMockRecorder struct {
	mock *Mockclock
}

// NewMockclock creates a new mock instance.
func NewMockclock(ctrl *gomock.Controller) *Mockclock {
	mock := &Mockclock{ctrl: ctrl}
	mock.recorder = &MockclockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclock) EXPECT() *MockclockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *Mockclock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockclockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*Mockclock)(nil).Now))
}

// MocktxManager is a mock of txManager interface.
type MocktxManager struct {
	ctrl     *gomock.Controller
	recorder *MocktxManagerMockRecorder
	isgomock struct{}
}

// MocktxManagerMockRecorder is the mock recorder for MocktxManager.
type MocktxManagerMockRecorder struct {
	mock *MocktxManager
}

// NewMocktxManager creates a new mock instance.
func NewMocktxManager(ctrl *gomock.Controller) *MocktxManager {
	mock := &MocktxManager{ctrl: ctrl}
	mock.recorder = &MocktxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktxManager) EXPECT() *MocktxManagerMockRecorder {
	return m.recorder
}

// WithinTx mocks base method.
func (m *MocktxManager) WithinTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTx indicates an expected call of WithinTx.
func (mr *MocktxManagerMockRecorder) WithinTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTx", reflect.TypeOf((*MocktxManager)(nil).WithinTx), ctx, fn)
}
