// Code generated by MockGen. DO NOT EDIT.
// Source: git.alva.dev/alva/harness-telemetry/internal/delivery/http/ingest (interfaces: Keys)
//
// Generated by this command:
//
//	mockgen -destination=mock/external.go -package=mock . Keys
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "git.alva.dev/alva/harness-telemetry/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockKeys is a mock of Keys interface.
type MockKeys struct {
	ctrl     *gomock.Controller
	recorder *MockKeysMockRecorder
	isgomock struct{}
}

// MockKeysMockRecorder is the mock recorder for MockKeys.
type MockKeysMockRecorder struct {
	mock *MockKeys
}

// NewMockKeys creates a new mock instance.
func NewMockKeys(ctrl *gomock.Controller) *MockKeys {
	mock := &MockKeys{ctrl: ctrl}
	mock.recorder = &MockKeysMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeys) EXPECT() *MockKeysMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockKeys) Resolve(ctx context.Context, kind domain.AccessKeyKind, plaintext string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, kind, plaintext)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockKeysMockRecorder) Resolve(ctx, kind, plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockKeys)(nil).Resolve), ctx, kind, plaintext)
}
