// Code generated by MockGen. DO NOT EDIT.
// Source: git.alva.dev/alva/harness-telemetry/internal/application/keys (interfaces: AccessKeys,TokenIssuer,Clock)
//
// Generated by this command:
//
//	mockgen -destination=mock/external.go -package=mock . AccessKeys,TokenIssuer,Clock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "git.alva.dev/alva/harness-telemetry/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessKeys is a mock of AccessKeys interface.
type MockAccessKeys struct {
	ctrl     *gomock.Controller
	recorder *MockAccessKeysMockRecorder
	isgomock struct{}
}

// MockAccessKeysMockRecorder is the mock recorder for MockAccessKeys.
type MockAccessKeysMockRecorder struct {
	mock *MockAccessKeys
}

// NewMockAccessKeys creates a new mock instance.
func NewMockAccessKeys(ctrl *gomock.Controller) *MockAccessKeys {
	mock := &MockAccessKeys{ctrl: ctrl}
	mock.recorder = &MockAccessKeysMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessKeys) EXPECT() *MockAccessKeysMockRecorder {
	return m.recorder
}

// Active mocks base method.
func (m *MockAccessKeys) Active(ctx context.Context, userID uuid.UUID, kind domain.AccessKeyKind) (domain.AccessKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Active", ctx, userID, kind)
	ret0, _ := ret[0].(domain.AccessKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Active indicates an expected call of Active.
func (mr *MockAccessKeysMockRecorder) Active(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Active", reflect.TypeOf((*MockAccessKeys)(nil).Active), ctx, userID, kind)
}

// FindByHash mocks base method.
func (m *MockAccessKeys) FindByHash(ctx context.Context, hash []byte) (domain.AccessKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, hash)
	ret0, _ := ret[0].(domain.AccessKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockAccessKeysMockRecorder) FindByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockAccessKeys)(nil).FindByHash), ctx, hash)
}

// Replace mocks base method.
func (m *MockAccessKeys) Replace(ctx context.Context, userID uuid.UUID, kind domain.AccessKeyKind, hash []byte, plaintext string) (domain.AccessKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, userID, kind, hash, plaintext)
	ret0, _ := ret[0].(domain.AccessKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockAccessKeysMockRecorder) Replace(ctx, userID, kind, hash, plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockAccessKeys)(nil).Replace), ctx, userID, kind, hash, plaintext)
}

// Revoke mocks base method.
func (m *MockAccessKeys) Revoke(ctx context.Context, userID uuid.UUID, kind domain.AccessKeyKind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, userID, kind)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAccessKeysMockRecorder) Revoke(ctx, userID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAccessKeys)(nil).Revoke), ctx, userID, kind)
}

// Touch mocks base method.
func (m *MockAccessKeys) Touch(ctx context.Context, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockAccessKeysMockRecorder) Touch(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockAccessKeys)(nil).Touch), ctx, id, at)
}

// MockTokenIssuer is a mock of TokenIssuer interface.
type MockTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenIssuerMockRecorder
	isgomock struct{}
}

// MockTokenIssuerMockRecorder is the mock recorder for MockTokenIssuer.
type MockTokenIssuerMockRecorder struct {
	mock *MockTokenIssuer
}

// NewMockTokenIssuer creates a new mock instance.
func NewMockTokenIssuer(ctrl *gomock.Controller) *MockTokenIssuer {
	mock := &MockTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenIssuer) EXPECT() *MockTokenIssuerMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockTokenIssuer) Hash(token string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", token)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockTokenIssuerMockRecorder) Hash(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockTokenIssuer)(nil).Hash), token)
}

// New mocks base method.
func (m *MockTokenIssuer) New() (string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// New indicates an expected call of New.
func (mr *MockTokenIssuerMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockTokenIssuer)(nil).New))
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
