/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Open without a session. Opens a session and sets its cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/login/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin signing in with a passkey
         * @description Open without a session. No email is asked: any discoverable passkey of a user answers. Sets the ht_webauthn cookie of the ceremony, which lives 5 minutes.
         */
        post: operations["beginPasskeyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/login/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish signing in with a passkey
         * @description Open without a session. Verifies the answer of the browser against the ceremony of the ht_webauthn cookie, opens a session, sets its cookie and deletes ht_webauthn.
         */
        post: operations["finishPasskeyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Closes the session of the request and deletes its cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the password of the signed-in user
         * @description Needs the current password; closes every other session of the user.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The passkeys of the signed-in user */
        get: operations["listMyPasskeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/passkeys/register/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin adding a passkey to the signed-in user
         * @description Sets the ht_webauthn cookie of the ceremony, which lives 5 minutes.
         */
        post: operations["beginPasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/passkeys/register/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish adding a passkey to the signed-in user
         * @description Verifies the answer of the browser against the ceremony of the ht_webauthn cookie, stores the passkey under the name given at the begin and deletes ht_webauthn.
         */
        post: operations["finishPasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/passkeys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a passkey of the signed-in user
         * @description The password stays, so the user can still sign in.
         */
        delete: operations["deleteMyPasskey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The state of the MCP key and the collector token of the signed-in user */
        get: operations["getMyKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/keys/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue the MCP key of the signed-in user
         * @description Issues a new MCP key and revokes the one the user had. Its open value is answered once: only its hash is kept.
         */
        post: operations["issueMyMcpKey"];
        /** Revoke the MCP key of the signed-in user */
        delete: operations["revokeMyMcpKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/keys/ingest/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reissue the collector token of the signed-in user
         * @description Issues a new collector token and revokes the one the user had: sending stops on every machine until the binary gets the new token through MCP. The open value is not answered here; only the binary gets it, through MCP.
         */
        post: operations["reissueMyIngestToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/telemetry-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The deny settings of the signed-in user and their version
         * @description The settings in full form, every field with its default included; the defaults and version 0 when the user has never saved settings.
         */
        get: operations["getMyTelemetrySettings"];
        /**
         * Save the deny settings of the signed-in user in place of the version they were read at
         * @description Saves settings in place of expectedVersion and tells the MCP subscribers of the user. An absent field takes its default. Settings equal to the stored ones keep the version.
         */
        put: operations["updateMyTelemetrySettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every user, invited ones included */
        get: operations["listUsers"];
        put?: never;
        /**
         * Invite a user
         * @description Creates an invited user and a one-time invitation link that lives 7 days.
         */
        post: operations["inviteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke the invitation
         * @description Deletes the invited user together with the invitation link.
         */
        delete: operations["revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reissue the invitation link
         * @description Issues a new invitation link; the previous one stops working.
         */
        post: operations["reissueInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a password reset link to another active user
         * @description Issues a one-time reset link that lives 7 days; the previous unused one stops working.
         */
        post: operations["issuePasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The token of a one-time link; never written to logs */
                token: components["parameters"]["LinkToken"];
            };
            cookie?: never;
        };
        /**
         * The user an invitation link was issued to
         * @description Open without a session.
         */
        get: operations["getInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The token of a one-time link; never written to logs */
                token: components["parameters"]["LinkToken"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept the invitation by setting a password
         * @description Open without a session. Uses the link up, signs the user in and sets the session cookie.
         */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password-resets/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The token of a one-time link; never written to logs */
                token: components["parameters"]["LinkToken"];
            };
            cookie?: never;
        };
        /**
         * The user a password reset link was issued to
         * @description Open without a session.
         */
        get: operations["getPasswordReset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password-resets/{token}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The token of a one-time link; never written to logs */
                token: components["parameters"]["LinkToken"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password by the reset link
         * @description Open without a session. Uses the link up, closes every session of the user, signs the user in and sets the session cookie.
         */
        post: operations["completePasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service build version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            email: string;
            password: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        BeginPasskeyLoginRequest: Record<string, never>;
        BeginPasskeyRegistrationRequest: {
            name: string;
        };
        PasskeyOptions: {
            /** @description The publicKey member of the options the browser passes to the authenticator */
            options: {
                [key: string]: unknown;
            };
        };
        PasskeyCredentialRequest: {
            /** @description The PublicKeyCredential of the browser, serialized to JSON */
            credential: {
                [key: string]: unknown;
            };
        };
        PasskeyItem: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string | null;
        };
        PasskeyList: {
            items: components["schemas"]["PasskeyItem"][];
        };
        KeyStatus: {
            /** @description The user has an active key of this kind */
            active: boolean;
            /**
             * Format: date-time
             * @description When the active key was created; null when there is none
             */
            createdAt: string | null;
            /**
             * Format: date-time
             * @description When the active key was last used, recorded at most once a minute; null until it is used or when there is none
             */
            lastUsedAt: string | null;
        };
        KeysStatus: {
            mcp: components["schemas"]["KeyStatus"];
            ingest: components["schemas"]["KeyStatus"];
        };
        IssuedMcpKey: {
            /** @description The open value of the MCP key; shown once and never answered again */
            key: string;
            /** @description The address of the MCP server, <HT_PUBLIC_ORIGIN>/mcp */
            mcpUrl: string;
            /** @description The name the MCP server is added to the agent under, hottell */
            serverName: string;
        };
        VersionedTelemetrySettings: {
            settings: components["schemas"]["TelemetrySettings"];
            /**
             * Format: int64
             * @description The version of the settings, kept by the server; 0 before the first save
             */
            version: number;
        };
        UpdateTelemetrySettingsRequest: {
            settings: components["schemas"]["TelemetrySettings"];
            /**
             * Format: int64
             * @description The version the settings were read at
             */
            expectedVersion: number;
        };
        InvalidTelemetrySettingsError: {
            /** @description invalid_telemetry_settings */
            code: string;
            /** @description Human-readable description */
            message: string;
            /** @description Where in the settings and why they break the schema, e.g. agents.claude.hook_events.denied[0] unknown hook event */
            detail: string;
        };
        /** @description The deny settings document of a user, as docs/specs/hottell-contract/settings.schema.json describes it. An absent field takes its default: everything is sent, history is not backfilled. The server checks the document itself, so the handler takes it as is. */
        TelemetrySettings: {
            /**
             * @description The version of the settings; kept by the server, never set by the client
             * @default 0
             */
            version: number;
            agents?: {
                claude?: components["schemas"]["ClaudeTelemetrySettings"];
                codex?: components["schemas"]["CodexTelemetrySettings"];
            };
            folders?: components["schemas"]["FolderRules"];
            /**
             * @description Kind 7 "backfill history"
             * @default false
             */
            backfill_history: boolean;
        };
        /** @description What is denied of Claude Code */
        ClaudeTelemetrySettings: {
            /**
             * @description Kind 1 "agent"; false turns the agent off entirely
             * @default true
             */
            enabled: boolean;
            sources?: components["schemas"]["TelemetrySources"];
            /** @description Kind 3 "hook event"; the denied hook_event_name of the agent */
            hook_events?: {
                /** @default [] */
                denied: components["schemas"]["ClaudeHookEvent"][];
            };
            hook_fields?: components["schemas"]["DeniedHookFields"];
            native_content?: components["schemas"]["DeniedNativeContent"];
        };
        /** @description What is denied of Codex CLI */
        CodexTelemetrySettings: {
            /**
             * @description Kind 1 "agent"; false turns the agent off entirely
             * @default true
             */
            enabled: boolean;
            sources?: components["schemas"]["TelemetrySources"];
            /** @description Kind 3 "hook event"; the denied hook_event_name of the agent */
            hook_events?: {
                /** @default [] */
                denied: components["schemas"]["CodexHookEvent"][];
            };
            hook_fields?: components["schemas"]["DeniedHookFields"];
            native_content?: components["schemas"]["DeniedNativeContent"];
        };
        /** @description Kind 2 "source"; false turns a source off */
        TelemetrySources: {
            /** @default true */
            hooks: boolean;
            /** @default true */
            transcripts: boolean;
            /** @default true */
            native_metrics: boolean;
            /** @default true */
            native_logs: boolean;
            /** @default true */
            native_traces: boolean;
        };
        /** @description Kind 4 "hook event field"; the denied top-level fields */
        DeniedHookFields: {
            /** @default [] */
            denied: components["schemas"]["HookField"][];
        };
        /** @description Kind 6 "native OTel content category" */
        DeniedNativeContent: {
            /** @default [] */
            denied: components["schemas"]["NativeContentCategory"][];
        };
        /** @description Kind 5 "project folder", shared by both agents */
        FolderRules: {
            /** @default [] */
            denied: components["schemas"]["FolderPattern"][];
            /** @default [] */
            allowed: components["schemas"]["FolderPattern"][];
        };
        /** @enum {string} */
        ClaudeHookEvent: "SessionStart" | "Setup" | "InstructionsLoaded" | "UserPromptSubmit" | "UserPromptExpansion" | "MessageDisplay" | "PreToolUse" | "PermissionRequest" | "PermissionDenied" | "PostToolUse" | "PostToolUseFailure" | "PostToolBatch" | "Notification" | "SubagentStart" | "SubagentStop" | "TaskCreated" | "TaskCompleted" | "Stop" | "StopFailure" | "TeammateIdle" | "ConfigChange" | "CwdChanged" | "DirectoryAdded" | "FileChanged" | "WorktreeCreate" | "WorktreeRemove" | "PreCompact" | "PostCompact" | "PreModelSwitch" | "PostModelSwitch" | "Elicitation" | "ElicitationResult" | "SessionEnd";
        /** @enum {string} */
        CodexHookEvent: "SessionStart" | "SessionEnd" | "UserPromptSubmit" | "PreToolUse" | "PermissionRequest" | "PostToolUse" | "PreCompact" | "PostCompact" | "SubagentStart" | "SubagentStop" | "Stop" | "Interrupt";
        /** @description A top-level field name; the service fields session_id, hook_event_name and cwd cannot be denied */
        HookField: string;
        /** @enum {string} */
        NativeContentCategory: "prompts" | "assistant_responses" | "tool_details" | "tool_content" | "raw_api_bodies";
        /** @description A path pattern starting with / or ~/; ** matches any number of segments */
        FolderPattern: string;
        UserListItem: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            status: "invited" | "active";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastLoginAt: string | null;
            /**
             * Format: date-time
             * @description Expiry of the unused invitation, past or not; null for an active user
             */
            inviteExpiresAt: string | null;
            /** @description The user is the signed-in one */
            isMe: boolean;
        };
        UserList: {
            items: components["schemas"]["UserListItem"][];
        };
        InviteUserRequest: {
            email: string;
            name: string;
        };
        InviteUserResponse: {
            user: components["schemas"]["UserListItem"];
            inviteUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        InviteLink: {
            inviteUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ResetLink: {
            resetUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        LinkHolder: {
            email: string;
            name: string;
        };
        SetPasswordRequest: {
            password: string;
        };
        Me: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
        };
        Version: {
            version: string;
        };
        /** @description The common body of every 4xx and 5xx response */
        Error: {
            /** @description Machine-readable error code, e.g. not_found */
            code: string;
            /** @description Human-readable description */
            message: string;
        };
    };
    responses: {
        /** @description passkey_verification_failed — the answer of the browser does not verify; passkey_ceremony_expired — no ceremony, or it expired or was finished already */
        PasskeyCeremonyFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description link_not_found — no such link */
        LinkNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description link_used or link_expired — the link cannot be used any more */
        LinkGone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Any 4xx or 5xx answer */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        UserID: string;
        /** @description The token of a one-time link; never written to logs */
        LinkToken: string;
        /** @description Kept with the session to tell the signed-in browsers apart */
        UserAgent: string;
        /** @description The ceremony begun by the matching begin operation; without it the answer is passkey_ceremony_expired */
        WebAuthnCeremony: string;
    };
    requestBodies: never;
    headers: {
        /** @description The ht_webauthn cookie of a WebAuthn ceremony, HttpOnly, SameSite=Strict and Path=/api; set on begin, deleted on finish */
        WebAuthnCookie: string;
        /** @description The ht_session cookie, HttpOnly and SameSite=Lax; set on sign-in, cleared on sign-out */
        SessionCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: {
                /** @description Kept with the session to tell the signed-in browsers apart */
                "User-Agent"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid_credentials — wrong email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    beginPasskeyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeginPasskeyLoginRequest"];
            };
        };
        responses: {
            /** @description The options for navigator.credentials.get */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["WebAuthnCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyOptions"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    finishPasskeyLogin: {
        parameters: {
            query?: never;
            header?: {
                /** @description Kept with the session to tell the signed-in browsers apart */
                "User-Agent"?: components["parameters"]["UserAgent"];
            };
            path?: never;
            cookie?: {
                /** @description The ceremony begun by the matching begin operation; without it the answer is passkey_ceremony_expired */
                ht_webauthn?: components["parameters"]["WebAuthnCeremony"];
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyCredentialRequest"];
            };
        };
        responses: {
            /** @description Signed in; Set-Cookie carries ht_session and the deleted ht_webauthn */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["PasskeyCeremonyFailed"];
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user of the session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description wrong_current_password, password_too_short or password_too_long */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMyPasskeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The passkeys, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    beginPasskeyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeginPasskeyRegistrationRequest"];
            };
        };
        responses: {
            /** @description The options for navigator.credentials.create */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["WebAuthnCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyOptions"];
                };
            };
            /** @description invalid_passkey_name — the name is not 1–64 characters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    finishPasskeyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description The ceremony begun by the matching begin operation; without it the answer is passkey_ceremony_expired */
                ht_webauthn?: components["parameters"]["WebAuthnCeremony"];
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyCredentialRequest"];
            };
        };
        responses: {
            /** @description The passkey added; Set-Cookie carries the deleted ht_webauthn */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["WebAuthnCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyItem"];
                };
            };
            400: components["responses"]["PasskeyCeremonyFailed"];
            default: components["responses"]["Error"];
        };
    };
    deleteMyPasskey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passkey deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description passkey_not_found — no such passkey of the user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether each key is active, when it was created and last used */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeysStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    issueMyMcpKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The open value of the key and where to connect the agent with it */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedMcpKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeMyMcpKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description access_key_not_found — the user has no active MCP key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reissueMyIngestToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token reissued */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMyTelemetrySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The settings and their version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionedTelemetrySettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateMyTelemetrySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTelemetrySettingsRequest"];
            };
        };
        responses: {
            /** @description The saved settings in full form and their new version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionedTelemetrySettings"];
                };
            };
            /** @description settings_version_conflict — the settings are no longer at expectedVersion */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description invalid_telemetry_settings — the settings break the schema; detail tells where and why */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidTelemetrySettingsError"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    inviteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteUserRequest"];
            };
        };
        responses: {
            /** @description The invited user and the invitation link */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteUserResponse"];
                };
            };
            /** @description invalid_email or invalid_name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description email_taken — another user has the email */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description user_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description user_not_invited — the user has accepted the invitation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reissueInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new invitation link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteLink"];
                };
            };
            /** @description user_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description user_not_invited — the user has accepted the invitation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    issuePasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reset link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetLink"];
                };
            };
            /** @description user_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description user_not_active — the invitation is not accepted; cannot_reset_self — the own password is changed in the profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The token of a one-time link; never written to logs */
                token: components["parameters"]["LinkToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invited user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkHolder"];
                };
            };
            404: components["responses"]["LinkNotFound"];
            410: components["responses"]["LinkGone"];
            default: components["responses"]["Error"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: {
                /** @description Kept with the session to tell the signed-in browsers apart */
                "User-Agent"?: components["parameters"]["UserAgent"];
            };
            path: {
                /** @description The token of a one-time link; never written to logs */
                token: components["parameters"]["LinkToken"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Invitation accepted, signed in */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description password_too_short or password_too_long */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["LinkNotFound"];
            410: components["responses"]["LinkGone"];
            default: components["responses"]["Error"];
        };
    };
    getPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The token of a one-time link; never written to logs */
                token: components["parameters"]["LinkToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user whose password the link resets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkHolder"];
                };
            };
            404: components["responses"]["LinkNotFound"];
            410: components["responses"]["LinkGone"];
            default: components["responses"]["Error"];
        };
    };
    completePasswordReset: {
        parameters: {
            query?: never;
            header?: {
                /** @description Kept with the session to tell the signed-in browsers apart */
                "User-Agent"?: components["parameters"]["UserAgent"];
            };
            path: {
                /** @description The token of a one-time link; never written to logs */
                token: components["parameters"]["LinkToken"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password set, signed in */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description password_too_short or password_too_long */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["LinkNotFound"];
            410: components["responses"]["LinkGone"];
            default: components["responses"]["Error"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version the service was built with */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
