// Code generated by MockGen. DO NOT EDIT.
// Source: git.alva.dev/alva/harness-telemetry/internal/delivery/mcp (interfaces: Keys,Users,Settings)
//
// Generated by this command:
//
//	mockgen -destination=mock/external.go -package=mock . Keys,Users,Settings
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "git.alva.dev/alva/harness-telemetry/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockKeys is a mock of Keys interface.
type MockKeys struct {
	ctrl     *gomock.Controller
	recorder *MockKeysMockRecorder
	isgomock struct{}
}

// MockKeysMockRecorder is the mock recorder for MockKeys.
type MockKeysMockRecorder struct {
	mock *MockKeys
}

// NewMockKeys creates a new mock instance.
func NewMockKeys(ctrl *gomock.Controller) *MockKeys {
	mock := &MockKeys{ctrl: ctrl}
	mock.recorder = &MockKeysMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeys) EXPECT() *MockKeysMockRecorder {
	return m.recorder
}

// IngestToken mocks base method.
func (m *MockKeys) IngestToken(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestToken", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestToken indicates an expected call of IngestToken.
func (mr *MockKeysMockRecorder) IngestToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestToken", reflect.TypeOf((*MockKeys)(nil).IngestToken), ctx, userID)
}

// Resolve mocks base method.
func (m *MockKeys) Resolve(ctx context.Context, kind domain.AccessKeyKind, plaintext string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, kind, plaintext)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockKeysMockRecorder) Resolve(ctx, kind, plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockKeys)(nil).Resolve), ctx, kind, plaintext)
}

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
	isgomock struct{}
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// Me mocks base method.
func (m *MockUsers) Me(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx, userID)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockUsersMockRecorder) Me(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockUsers)(nil).Me), ctx, userID)
}

// MockSettings is a mock of Settings interface.
type MockSettings struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsMockRecorder
	isgomock struct{}
}

// MockSettingsMockRecorder is the mock recorder for MockSettings.
type MockSettingsMockRecorder struct {
	mock *MockSettings
}

// NewMockSettings creates a new mock instance.
func NewMockSettings(ctrl *gomock.Controller) *MockSettings {
	mock := &MockSettings{ctrl: ctrl}
	mock.recorder = &MockSettingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettings) EXPECT() *MockSettingsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSettings) Get(ctx context.Context, userID uuid.UUID) (domain.TelemetrySettings, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.TelemetrySettings)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockSettingsMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettings)(nil).Get), ctx, userID)
}

// Subscribe mocks base method.
func (m *MockSettings) Subscribe(ctx context.Context, userID uuid.UUID) <-chan int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, userID)
	ret0, _ := ret[0].(<-chan int64)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSettingsMockRecorder) Subscribe(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSettings)(nil).Subscribe), ctx, userID)
}
